name: Andrew Kennedy
url: http://akenn.org
description: >
  My name is Andrew Kennedy. I make music, write software, and blog about both.
  During the day I'm a Frontend Engineer at CloudFlare.  At night I work on
  open source projects, record music, and play video games.
permalink: /blog/:title
twitter: helpybot
github: akenn
gravatar_url: http://gravatar.com/avatar/f09cff58b90ec70b34605afb26a5964d

exclude: [PSDs/]
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
