name: Andrew Kennedy
url: http://akenn.org
description: An amazing blog that is amazing.
permalink: /blog/:title
twitter: L1fescape
github: L1fescape
gravatar_url: http://gravatar.com/avatar/f09cff58b90ec70b34605afb26a5964d

exclude: [PSDs/]
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
