name: Andrew Kennedy
url: http://akenn.org
description: >
  My name is Andrew Kennedy. I make music, write software, and blog about both.
  During the day I'm a Frontend Engineer at CloudFlare.  At night I work on
  open source projects and record music.
permalink: /blog/:title
gravatar_url: http://gravatar.com/avatar/f09cff58b90ec70b34605afb26a5964d
social:
  email: andrew@akenn.org
  twitter: L1fescape
  github: akenn
  keybase: akenn
  soundcloud: L1fescape
  gplus: 113415129270300199292
  reddit: L1fescape
  linkedin: 194622112

exclude: [PSDs/]

highlighter: true
